version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: servo-postgres
    restart: always
    environment:
      POSTGRES_DB: servo_db
      POSTGRES_USER: servo_user
      POSTGRES_PASSWORD: servo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: