spring.application.name=api
spring.profiles.active=local

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

discord.client-id=1469525847919821026
discord.client-secret=JYnbDReh3sNoYKj1hyp2IYbR53WWRuHf
discord.guild-id=1474804663004958740
discord.redirect-uri=http://localhost:8080/auth/discord/callback
discord.frontend-url=http://localhost:5173

jwt.expiration=86400000

# https://discord.com/oauth2/authorize?client_id=1469525847919821026&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Flogin%2Foauth2%2Fcode%2Fdiscord&scope=identify+guilds+email+guilds.members.read
# https://discord.com/oauth2/authorize?client_id=1469525847919821026&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Flogin%2Foauth2%2Fcode%2Fdiscord&scope=identify+guilds+email+guilds.members.read

spring.datasource.url=jdbc:postgresql://localhost:5432/servo_db
spring.datasource.username=servo_user
spring.datasource.password=servo_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false