spring.application.name=api
spring.profiles.active=local

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.jpa.properties.hibernate.show_sql=false

discord.client-id=1469525847919821026
discord.client-secret=JYnbDReh3sNoYKj1hyp2IYbR53WWRuHf
discord.guild-id=1432454782278434931
discord.redirect-uri=https://bernita-napless-datedly.ngrok-free.dev/auth/discord/callback
discord.frontend-url=http://localhost:3000

jwt.expiration=86400000

# https://discord.com/oauth2/authorize?client_id=1469525847919821026&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Flogin%2Foauth2%2Fcode%2Fdiscord&scope=identify+guilds+email+guilds.members.read
# https://discord.com/oauth2/authorize?client_id=1469525847919821026&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Flogin%2Foauth2%2Fcode%2Fdiscord&scope=identify+guilds+email+guilds.members.read

spring.datasource.url=jdbc:postgresql://localhost:5432/servo_db
spring.datasource.username=servo_user
spring.datasource.password=servo_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=110MB
upload.dir=uploads
upload.base-url=https://bernita-napless-datedly.ngrok-free.dev/uploads